//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityForm
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public int ActivityId { get; set; }
        public System.Guid Guid { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Form Form { get; set; }
    }
}
