//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Activity1 = new HashSet<Activity>();
            this.ActivityEntityTypes = new HashSet<ActivityEntityType>();
            this.ActivityForms = new HashSet<ActivityForm>();
            this.ActivitySchedulings = new HashSet<ActivityScheduling>();
            this.ActivitySchedulings1 = new HashSet<ActivityScheduling>();
            this.AddActivities = new HashSet<AddActivity>();
            this.FormDataEntries = new HashSet<FormDataEntry>();
            this.ProjectBuilderJSONEntityValues = new HashSet<ProjectBuilderJSONEntityValue>();
        }
    
        public int Id { get; set; }
        public string ActivityName { get; set; }
        public Nullable<int> RepeatationType { get; set; }
        public Nullable<int> RepeatationCount { get; set; }
        public Nullable<int> RepeatationOffset { get; set; }
        public Nullable<int> DependentActivityId { get; set; }
        public Nullable<int> ActivityCategoryId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ScheduleType { get; set; }
        public int ActivityStatusId { get; set; }
        public int ProjectId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<bool> PreviewSchedulingDone { get; set; }
        public int IsDefaultActivity { get; set; }
        public Nullable<bool> IsActivityRequireAnEntity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity1 { get; set; }
        public virtual Activity Activity2 { get; set; }
        public virtual ActivityCategory ActivityCategory { get; set; }
        public virtual ActivityStatu ActivityStatu { get; set; }
        public virtual FormDataEntry FormDataEntry { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityEntityType> ActivityEntityTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityForm> ActivityForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityScheduling> ActivitySchedulings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityScheduling> ActivitySchedulings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddActivity> AddActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDataEntry> FormDataEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBuilderJSONEntityValue> ProjectBuilderJSONEntityValues { get; set; }
    }
}
