//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityScheduling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityScheduling()
        {
            this.RoleToCreateActivityRegardlessScheduleds = new HashSet<RoleToCreateActivityRegardlessScheduled>();
            this.RolesToCreateActivitySchedulings = new HashSet<RolesToCreateActivityScheduling>();
        }
    
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public int ScheduledToBeCompleted { get; set; }
        public int ActivityAvailableForCreation { get; set; }
        public int RolesToCreateActivity { get; set; }
        public int RoleToCreateActivityRegardlessScheduled { get; set; }
        public Nullable<int> OtherActivity { get; set; }
        public Nullable<int> OffsetCount { get; set; }
        public Nullable<int> OffsetType { get; set; }
        public Nullable<int> SpecifiedActivity { get; set; }
        public Nullable<int> CreationWindowOpens { get; set; }
        public Nullable<int> CreationWindowClose { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<bool> IsScheduled { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> Status { get; set; }
        public int ProjectId { get; set; }
        public bool CanCreatedMultipleTime { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Activity Activity1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleToCreateActivityRegardlessScheduled> RoleToCreateActivityRegardlessScheduleds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesToCreateActivityScheduling> RolesToCreateActivitySchedulings { get; set; }
        public virtual FormDataEntry FormDataEntry { get; set; }
    }
}
