//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddActivity
    {
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public int ActivityCompletedByUser { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public Nullable<bool> IsActivityAdded { get; set; }
        public int ProjectId { get; set; }
        public int PersonEntityId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public System.Guid Guid { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual FormDataEntry FormDataEntry { get; set; }
        public virtual FormDataEntry FormDataEntry1 { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
