//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int Id { get; set; }
        public string To { get; set; }
        public string From { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsSend { get; set; }
        public Nullable<int> FailedAttempt { get; set; }
        public bool IsImmediate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public int SmtpServerId { get; set; }
        public System.Guid Guid { get; set; }
    
        public virtual SmtpServer SmtpServer { get; set; }
    }
}
