//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityType
    {
        public EntityType()
        {
            this.EntitySubTypes = new HashSet<EntitySubType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<int> TenantId { get; set; }
    
        public virtual ICollection<EntitySubType> EntitySubTypes { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
