//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityFormDataVariable
    {
        public int Id { get; set; }
        public int EntityId { get; set; }
        public int VariableId { get; set; }
        public string SelectedValues { get; set; }
        public string EntityName { get; set; }
        public int EntityTypeId { get; set; }
        public Nullable<int> EntitySubTypeId { get; set; }
        public string Json { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public System.Guid Guid { get; set; }
    
        public virtual Variable Variable { get; set; }
    }
}
