//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Log
    {
        public Nullable<int> error_number { get; set; }
        public Nullable<int> error_state { get; set; }
        public string error_procedure { get; set; }
        public Nullable<int> error_line { get; set; }
        public string error_message { get; set; }
        public System.DateTime Created { get; set; }
    }
}
