//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormVariableRole
    {
        public int Id { get; set; }
        public int FormVariableId { get; set; }
        public int RoleId { get; set; }
        public System.Guid Guid { get; set; }
        public bool CanCreate { get; set; }
        public bool CanView { get; set; }
        public bool CanEdit { get; set; }
        public bool CanDelete { get; set; }
    
        public virtual FormVariable FormVariable { get; set; }
        public virtual Role Role { get; set; }
    }
}
