//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormDataEntryVariable
    {
        public int Id { get; set; }
        public int VariableId { get; set; }
        public string SelectedValues { get; set; }
        public Nullable<int> SelectedValues_int { get; set; }
        public Nullable<double> SelectedValues_float { get; set; }
        public int FormDataEntryId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual FormDataEntry FormDataEntry { get; set; }
        public virtual Variable Variable { get; set; }
    }
}
