//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormDataEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormDataEntry()
        {
            this.Activities = new HashSet<Activity>();
            this.ActivitySchedulings = new HashSet<ActivityScheduling>();
            this.AddActivities = new HashSet<AddActivity>();
            this.AddActivities1 = new HashSet<AddActivity>();
            this.Forms = new HashSet<Form>();
            this.FormDataEntryVariables = new HashSet<FormDataEntryVariable>();
            this.ProjectBuilderJSONs = new HashSet<ProjectBuilderJSON>();
            this.ProjectBuilderJSONEntityValues = new HashSet<ProjectBuilderJSONEntityValue>();
            this.ProjectStaffMemberRoles = new HashSet<ProjectStaffMemberRole>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int EntityId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public int Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<int> FormId { get; set; }
        public Nullable<int> ThisUserId { get; set; }
        public Nullable<int> EntityNumber { get; set; }
        public Nullable<int> ParentEntityNumber { get; set; }
        public Nullable<int> ProjectDeployStatus { get; set; }
        public string ProjectDeployedId { get; set; }
        public string ProjectDeployedVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityScheduling> ActivitySchedulings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddActivity> AddActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddActivity> AddActivities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form> Forms { get; set; }
        public virtual Form Form { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDataEntryVariable> FormDataEntryVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBuilderJSON> ProjectBuilderJSONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBuilderJSONEntityValue> ProjectBuilderJSONEntityValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStaffMemberRole> ProjectStaffMemberRoles { get; set; }
    }
}
