//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form()
        {
            this.ActivityForms = new HashSet<ActivityForm>();
            this.FormDataEntries = new HashSet<FormDataEntry>();
            this.FormEntityTypes = new HashSet<FormEntityType>();
            this.FormVariables = new HashSet<FormVariable>();
            this.ProjectBuilderJSONEntityValues = new HashSet<ProjectBuilderJSONEntityValue>();
            this.ReviewerFeedbacks = new HashSet<ReviewerFeedback>();
        }
    
        public int Id { get; set; }
        public string FormTitle { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public bool IsTemplate { get; set; }
        public Nullable<int> FormCategoryId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int FormState { get; set; }
        public int FormStatusId { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> PreviousVersion { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<int> TenantId { get; set; }
        public int IsDefaultForm { get; set; }
        public string FormComposeDetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityForm> ActivityForms { get; set; }
        public virtual FormDataEntry FormDataEntry { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDataEntry> FormDataEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormEntityType> FormEntityTypes { get; set; }
        public virtual FormCategory FormCategory { get; set; }
        public virtual FormStatu FormStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormVariable> FormVariables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBuilderJSONEntityValue> ProjectBuilderJSONEntityValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewerFeedback> ReviewerFeedbacks { get; set; }
    }
}
