//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupDataOptionGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookupDataOptionGroup()
        {
            this.LookupDataGroupOptions = new HashSet<LookupDataGroupOption>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public string Value { get; set; }
        public int LookupDataId { get; set; }
        public System.Guid Guid { get; set; }
    
        public virtual LookupData LookupData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LookupDataGroupOption> LookupDataGroupOptions { get; set; }
    }
}
