//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostCode
    {
        public int Id { get; set; }
        public string PostalCode { get; set; }
        public int SuburbId { get; set; }
        public int CityId { get; set; }
        public int StateId { get; set; }
        public System.Guid Guid { get; set; }
    
        public virtual City City { get; set; }
        public virtual State State { get; set; }
        public virtual Suburb Suburb { get; set; }
    }
}
