//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStaffMemberRole
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public int CreatedBy { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<System.DateTime> StaffCreatedDate { get; set; }
        public Nullable<bool> IsActiveProjectUser { get; set; }
        public Nullable<System.DateTime> ProjectJoinedDate { get; set; }
        public Nullable<System.DateTime> ProjectLeftDate { get; set; }
    
        public virtual FormDataEntry FormDataEntry { get; set; }
        public virtual Role Role { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual UserLogin UserLogin1 { get; set; }
    }
}
