//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.EntityTypes = new HashSet<EntityType>();
            this.Roles = new HashSet<Role>();
            this.Variables = new HashSet<Variable>();
            this.VariableCategories = new HashSet<VariableCategory>();
        }
    
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
    
        public virtual ICollection<EntityType> EntityTypes { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Variable> Variables { get; set; }
        public virtual ICollection<VariableCategory> VariableCategories { get; set; }
    }
}
