//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TestAspreeEntities : DbContext
    {
        public TestAspreeEntities()
            : base("name=TestAspreeEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityCategory> ActivityCategories { get; set; }
        public virtual DbSet<ActivityEntityType> ActivityEntityTypes { get; set; }
        public virtual DbSet<ActivityForm> ActivityForms { get; set; }
        public virtual DbSet<ActivityScheduling> ActivitySchedulings { get; set; }
        public virtual DbSet<ActivityStatu> ActivityStatus { get; set; }
        public virtual DbSet<AuthTypeMaster> AuthTypeMasters { get; set; }
        public virtual DbSet<CheckList> CheckLists { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<EntityFormDataVariable> EntityFormDataVariables { get; set; }
        public virtual DbSet<EntitySubType> EntitySubTypes { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<EntityVariable> EntityVariables { get; set; }
        public virtual DbSet<ExternalLink> ExternalLinks { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<FormCategory> FormCategories { get; set; }
        public virtual DbSet<FormDataEntry> FormDataEntries { get; set; }
        public virtual DbSet<FormDataEntryVariable> FormDataEntryVariables { get; set; }
        public virtual DbSet<FormEntityType> FormEntityTypes { get; set; }
        public virtual DbSet<FormStatu> FormStatus { get; set; }
        public virtual DbSet<FormVariable> FormVariables { get; set; }
        public virtual DbSet<FormVariableRole> FormVariableRoles { get; set; }
        public virtual DbSet<LoginAuthTypeMaster> LoginAuthTypeMasters { get; set; }
        public virtual DbSet<LookupData> LookupDatas { get; set; }
        public virtual DbSet<LookupDataGroupOption> LookupDataGroupOptions { get; set; }
        public virtual DbSet<LookupDataOptionGroup> LookupDataOptionGroups { get; set; }
        public virtual DbSet<PostCode> PostCodes { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectCheckList> ProjectCheckLists { get; set; }
        public virtual DbSet<ProjectEntityType> ProjectEntityTypes { get; set; }
        public virtual DbSet<ProjectParticipant> ProjectParticipants { get; set; }
        public virtual DbSet<ProjectRole> ProjectRoles { get; set; }
        public virtual DbSet<ProjectSite> ProjectSites { get; set; }
        public virtual DbSet<ProjectStaffMember> ProjectStaffMembers { get; set; }
        public virtual DbSet<ProjectStaffMemberRole> ProjectStaffMemberRoles { get; set; }
        public virtual DbSet<ProjectStatu> ProjectStatus { get; set; }
        public virtual DbSet<PushEmailEvent> PushEmailEvents { get; set; }
        public virtual DbSet<RegExRule> RegExRules { get; set; }
        public virtual DbSet<ReviewerFeedback> ReviewerFeedbacks { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolePrivilege> RolePrivileges { get; set; }
        public virtual DbSet<RolesToCreateActivityScheduling> RolesToCreateActivitySchedulings { get; set; }
        public virtual DbSet<RoleToCreateActivityRegardlessScheduled> RoleToCreateActivityRegardlessScheduleds { get; set; }
        public virtual DbSet<SchedulingTypeMaster> SchedulingTypeMasters { get; set; }
        public virtual DbSet<SecurityQuestion> SecurityQuestions { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SmtpServer> SmtpServers { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Suburb> Suburbs { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ValidationRule> ValidationRules { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
        public virtual DbSet<VariableApprovalLog> VariableApprovalLogs { get; set; }
        public virtual DbSet<VariableCategory> VariableCategories { get; set; }
        public virtual DbSet<VariableEntityType> VariableEntityTypes { get; set; }
        public virtual DbSet<VariableRole> VariableRoles { get; set; }
        public virtual DbSet<VariableType> VariableTypes { get; set; }
        public virtual DbSet<VariableValidationRule> VariableValidationRules { get; set; }
        public virtual DbSet<VariableValue> VariableValues { get; set; }
    }
}
