//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserLogin()
        {
            this.AddActivities = new HashSet<AddActivity>();
            this.FormDataEntries = new HashSet<FormDataEntry>();
            this.ProjectStaffMembers = new HashSet<ProjectStaffMember>();
            this.ProjectStaffMemberRoles = new HashSet<ProjectStaffMemberRole>();
            this.ProjectStaffMemberRoles1 = new HashSet<ProjectStaffMemberRole>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public Nullable<int> SecurityQuestionId { get; set; }
        public string Answer { get; set; }
        public string AccessToken { get; set; }
        public int TenantId { get; set; }
        public int AuthTypeId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> TempGuid { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsMailSend { get; set; }
        public Nullable<bool> IsApiAccessEnabled { get; set; }
        public bool IsUserApprovedBySystemAdmin { get; set; }
        public Nullable<int> LoginFailedAttemptCount { get; set; }
        public Nullable<System.DateTime> LoginFailedAttemptDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddActivity> AddActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDataEntry> FormDataEntries { get; set; }
        public virtual LoginAuthTypeMaster LoginAuthTypeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStaffMember> ProjectStaffMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStaffMemberRole> ProjectStaffMemberRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStaffMemberRole> ProjectStaffMemberRoles1 { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
