//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspree.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableType
    {
        public VariableType()
        {
            this.Variables = new HashSet<Variable>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public int Status { get; set; }
        public System.Guid Guid { get; set; }
    
        public virtual ICollection<Variable> Variables { get; set; }
    }
}
